name: Salesforce Deployment Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

    secrets:
      ENCRYPTION_KEY_FILE:
        required: true
      JWT_KEY_FILE:
        required: true
      DECRYPTION_KEY:
        required: true
      DECRYPTION_IV:
        required: true
      CONSUMER_KEY:
        required: true
      DEPLOYMENT_USER_USERNAME:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run common Salesforce setup which calls the Salesforce Common Setup action
      - name: Run Common Salesforce Setup
        uses: ./.github/actions/salesforce-common
        with:
          node_version: ${{ vars.NODE_VERSION }}
          java_version: ${{ vars.JAVA_VERSION }}
          python_version: ${{ vars.PYTHON_VERSION }}
          sf_cli_version: ${{ vars.SF_CLI_VERSION }}
          encryption_key_file: ${{ secrets.ENCRYPTION_KEY_FILE }}
          jwt_key_file: ${{ secrets.JWT_KEY_FILE }}
          decryption_key: ${{ secrets.DECRYPTION_KEY }}
          decryption_iv: ${{ secrets.DECRYPTION_IV }}
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          deployment_username: ${{ secrets.DEPLOYMENT_USER_USERNAME }}
          org_alias: ${{ vars.ORG_DEFAULT_ALIAS }}
          instance_url: ${{ vars.HUB_LOGIN_URL }}
          delta_from: ${{ github.event.before }}
          delta_to: ${{ github.sha }}

      # Deploy delta to Salesforce
      - name: Deploy Delta to Salesforce
        run: |
          sf project deploy start \
            --source-dir delta/force-app/main/default \
            --target-org "${{ vars.ORG_DEFAULT_ALIAS }}" \
            --ignore-conflicts \
            --wait 45

      # Send Slack Notification on Success
      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Deployment successful for ${{ inputs.environment }}"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "Deployment successful for ${{ inputs.environment }}"
              - type: "section"
                fields:
                  - type: "mrkdwn"
                    text: "*Environment*\n${{ inputs.environment }}"
                  - type: "mrkdwn"
                    text: "*Deployment Type*\nDelta"
                  - type: "mrkdwn"
                    text: "*Deployment Status*\nSuccess"
                  - type: "mrkdwn"
                    text: "*Deployment Time*\n${{ github.event.head_commit.timestamp }}"
                  - type: "mrkdwn"
                    text: "*Deployment User*\n${{ github.event.head_commit.author.name }}"
                  - type: "mrkdwn"
                    text: "*Deployment Commit*\n`${{ github.event.head_commit.id }}`" 