name: Salesforce Feature Branch CI/CD Pipeline

run-name: "Salesforce Feature Branch CI/CD Pipeline Running"

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - feature/**

jobs:
  build-salesforce:
    uses: ./.github/workflows/template.yaml
    with:
      environment: dev
    secrets: inherit
    #secrets: if we want to use some template specific secrets set these in the template.yaml file and input them here.
    #  - SLACKNAME
    #  - SLACKWEBHOOK