name: Salesforce Dev CI/CD Pipeline

run-name: "Salesforce Dev CI/CD Pipeline Running"

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - dev

  pull_request:
    branches:
      - dev
    paths:
      - 'force-app/**'  
    types:
      - opened
      - closed

jobs:
  build-salesforce:
    uses: ./.github/workflows/template.yaml
    with:
      environment: dev
    secrets: inherit