name: Salesforce Dev CI/CD Pipeline

run-name: "Salesforce Dev CI/CD Pipeline Running"

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - dev

  pull_request:
    branches:
      - dev
    paths:
      - 'force-app/**'  
    types:
      - opened
      - closed

jobs:
  build-salesforce:
    name: Build & Validate Salesforce Code
    uses: ./.github/workflows/template.yaml
    with:
      environment: dev
    secrets:
      ENCRYPTION_KEY_FILE: ${{ secrets.ENCRYPTION_KEY_FILE }}
      JWT_KEY_FILE: ${{ secrets.JWT_KEY_FILE }}
      DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
      DECRYPTION_IV: ${{ secrets.DECRYPTION_IV }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      DEPLOYMENT_USER_USERNAME: ${{ secrets.DEPLOYMENT_USER_USERNAME }}