name: Production Pipeline
run-name: "Production Pipeline Running"

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'
    

  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'  
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-salesforce:
    name: Build & Validate Salesforce Code
    uses: ./.github/workflows/template.yaml
    with:
      environment: production
      deploy: ${{ github.event_name == 'push' }}
    secrets:
      ENCRYPTION_KEY_FILE: ${{ secrets.ENCRYPTION_KEY_FILE }}
      JWT_KEY_FILE: ${{ secrets.JWT_KEY_FILE }}
      DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
      DECRYPTION_IV: ${{ secrets.DECRYPTION_IV }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      DEPLOYMENT_USER_USERNAME: ${{ secrets.DEPLOYMENT_USER_USERNAME }}