name: Salesforce Main Branch CI/CD Pipeline
run-name: "Salesforce Main Branch CI/CD Pipeline Running"

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'  
    types:
      - opened
      - closed

jobs:
  build-salesforce:
    name: Build & Validate Salesforce Code
    uses: ./.github/workflows/template.yaml
    with:
      environment: production
    secrets: inherit