name: Salesforce UAT CI/CD Pipeline
run-name: "Salesforce UAT CI/CD Pipeline Running"

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - uat

  pull_request:
    branches:
      - uat
    paths:
      - 'force-app/**'  
    types:
      - opened
      - closed

jobs:
  build-salesforce:
    name: Build & Validate Salesforce Code
    uses: ./.github/workflows/template.yaml
    with:
      environment: uat
    secrets: inherit