name: Common Pipeline Template

on:
  workflow_call:
    inputs:
      environment:
        description: The environment to build the code for
        required: true
        default: "dev"
        type: string
      deploy:
        description: Whether to deploy the code to the environment
        required: true
        default: true
        type: boolean
    secrets:
      ENCRYPTION_KEY_FILE:
        description: Encrypted JWT key file path
        required: true
      JWT_KEY_FILE:
        description: Decrypted JWT key file path
        required: true
      DECRYPTION_KEY:
        description: AES decryption key
        required: true
      DECRYPTION_IV:
        description: AES initialization vector
        required: true
      CONSUMER_KEY:
        description: Salesforce Connected App consumer key
        required: true
      DEPLOYMENT_USER_USERNAME:
        description: Salesforce deployment username
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

       # PREREQUISITES - Only needed if the runner doesn't already satisfy these requirements.
      - name: Ensure node v20.9.0 or greater
        uses: actions/setup-node@v5
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Ensure java v11 or greater
        uses: actions/setup-java@v5
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: 'zulu'
      - name: Ensure python v3.10 or greater
        uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.PYTHON_VERSION }}


      # Read PR Details and Create File to Extract Apex Test Classes to Run
      - name: Read PR Details and Create File to Extract Apex Test Classes to Run
        run: |
          echo "${{ github.event.pull_request.body }}" >> pr_body.txt
          python READ_PRBODY.py > output.txt
          cat output.txt
          echo "apex_test_classes=$(cat output.txt)" >> $GITHUB_ENV
          echo "${{ env.apex_test_classes }}"

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli@${{ vars.SF_CLI_VERSION }}

      # Check Salesforce CLI Version
      - name: Check Salesforce CLI Version
        run: |
          sf --version

      # Install Salesforce Code Analyzer
      - name: Install Salesforce Code Analyzer
        run: |
          sf plugins install code-analyzer

      # Install SFDX Git Delta
      - name: Install SFDX Git Delta
        run: echo 'Y' | sf plugins install sfdx-git-delta

      # Before running create the folder called delta and then generate the delta file, we use the HEAD~1 to HEAD delta to get the latest changes and then we use the delta to deploy the changes to the Salesforce org
      # This is to avoid the issue of the delta file being too large and causing the deploy to fail
      # We also use the ignore-file .sgdignore to ignore the files that are not needed in the delta file
      # We also use the ignore-whitespace to ignore the whitespace changes in the delta file
      # We also use the api-version 66.0 to use the latest API version
      # We also use the source-dir force-app/main/default to specify the source directory
      # We also use the output-dir ./delta to specify the output directory
      # We also use the generate-delta to generate the delta file
      - name: Generate Delta File
        run: |
          mkdir delta
          sf sgd source delta \
          --from "HEAD~1" --to "HEAD" \
          --generate-delta --ignore-file .sgdignore \
          --output-dir ./delta --ignore-whitespace --api-version 66.0 \
          --source-dir force-app/main/default
          cat delta/package/package.xml
          ls delta
          
      # Run Code Analyzer
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace . --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      # Decrypt the encrypted JWT key file
      - name: Decrypt the encrypted JWT key file
        run: |
         openssl enc -nosalt -aes-256-cbc -d -in ${{secrets.ENCRYPTION_KEY_FILE}} -out ${{secrets.JWT_KEY_FILE}} -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
       
      # Authenticate with Salesforce
      - name: Authenticate Salesforce with JWT
        run: |
          sf org login jwt --client-id ${{secrets.CONSUMER_KEY}} --jwt-key-file ${{secrets.JWT_KEY_FILE}} --username ${{secrets.DEPLOYMENT_USER_USERNAME}} --set-default --alias ${{vars.ORG_DEFAULT_ALIAS}} --instance-url ${{vars.HUB_LOGIN_URL}}

      # Verify Salesforce Org Information
      - name: Verify Salesforce Org is Authenticated
        run: |
          sf org display --target-org ${{vars.ORG_DEFAULT_ALIAS}} --json

      # Before running the deploy or validate, we need to check if the PR is merged or not
      # if PR is raised and not merged, then validate the changes to the Salesforce org
      # if PR is merged, then deploy the changes to the Salesforce org
      # Validate to Salesforce ORG - With Specific Tests, or Default Test Level or RunRelevantTests
      - name: "Validate to Salesforce ORG - With Specific Tests"
        if: ${{ env.apex_test_classes != 'No Apex classes found' && github.event.pull_request.merged == false && github.event_name == 'pull_request' }}
        run: |
          sf project deploy start --test-level RunSpecifiedTests \
            --tests ${{ env.apex_test_classes }} \
            --source-dir delta/force-app/main/default \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} --wait 45 \
            --dry-run --json 2>&1 | tee deploy-result.json
          
      - name: "Validate to Salesforce org - Default Test Level"
        if: ${{ env.apex_test_classes == 'No Apex classes found' && github.event.pull_request.merged == false && github.event_name == 'pull_request' }}
        run: |
          sf project deploy start \
            --source-dir delta/force-app/main/default \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} \
            --wait 45 \
            --dry-run --json 2>&1 | tee deploy-result.json

      - name: "Validate to Salesforce ORG - RunRelevantTests"
        if: ${{ env.apex_test_classes == 'RunRelevantTests' && github.event.pull_request.merged == false && github.event_name == 'pull_request' }}
        run: |
          sf project deploy start --test-level RunRelevantTests \
            --source-dir delta/force-app/main/default  \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} --wait 45 \
            --dry-run --json 2>&1 | tee deploy-result.json

      # Enforce 80% code coverage
      - name: "Enfore 80% code coverage"
        if: ${{ github.event.pull_request.merged == false && github.event_name == 'pull_request' }}
        run: |
          python CODE_COVERAGE.py sfca_results.json

      # Deploy to Salesforce ORG - RunRelevantTests or Default Test Level or With Specific Tests
      # if PR is merged, then deploy the changes to the Salesforce org
      - name: "Deploy to Salesforce ORG - RunRelevantTests"
        if: ${{ env.apex_test_classes == 'RunRelevantTests'  && github.event.pull_request.merged == true && github.event_name == 'pull_request'}}
        run: |
          sf project deploy start --test-level RunRelevantTests \
            --source-dir delta/force-app/main/default  \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} \
            --ignore-conflicts --wait 45

      - name: "Deploy to Salesforce org - Default Test Level"
        if: ${{ env.apex_test_classes == 'No Apex classes found' && github.event.pull_request.merged == true && github.event_name == 'pull_request'}}
        run: |
          sf project deploy start \
            --source-dir delta/force-app/main/default \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} \
            --ignore-conflicts --wait 45

      - name: "Deploy to Salesforce ORG - With Specific Tests"
        if: ${{ env.apex_test_classes != 'No Apex classes found' && github.event.pull_request.merged == true && github.event_name == 'pull_request'}}
        run: |
          sf project deploy start --test-level RunSpecifiedTests \
            --tests ${{ env.apex_test_classes }} \
            --source-dir delta/force-app/main/default \
            --target-org ${{ vars.ORG_DEFAULT_ALIAS }} \
            --ignore-conflicts --wait 45